### ISSUE TITLE
DENON AV Reciever & One more generic telnet request

### ISSUE THREAD

**Issue by theColourSpace** [bitfocus/companion-module-denon-receiver#1]
Hi All,

New to companion. I want to say that this seems like a great platform, and it's good to see so much dev and energy. I'm trying to control a Denon Surround processor, it uses simple telnet commands to control the volume/input etc. 

Documented here: https://usa.denon.com/us/product/hometheater/receivers/avr3808ci?docname=AVR-3808CISerialProtocol_Ver520a.pdf

I would just add, that this could be made simple to add, and it would help others developing in the module format if you provided a generic telnet template module with instructions on how to implement, and contribute to the code.

That way folks could mod code to work with their devices then submit their code to the project for addition. Win/Win.

**Comment by JeffreyDavidsz** [comment]
@theColourSpace module is in the core now please test it and let us know if this works for you

**Comment by theColourSpace** [comment]
From my brief testing it seems the volume down command isn't working. The others I've tried (mute on/off, Volume Up) work great.

**Comment by theColourSpace** [comment]
From the companion log, it seems the command isn't found: 2019-04-09T19:45:05.065Z lib/action trying to run bank 1 1 true +433ms
2019-04-09T19:45:05.066Z lib/action found actions +1ms
2019-04-09T19:45:05.088Z lib/bank being told from gui to hot press 1 1 false +75ms
2019-04-09T19:45:05.141Z lib/action trying to run bank 1 1 false +75ms

**Comment by theColourSpace** [comment]
Looking at the code, there's two issues, the Volume Down function is mislabeled as "Colume Down"... and the actual call is misidentified as a mute command:
case 'volume':
			if (opt.volume == 'volume_up') {
				cmd = 'MVUP\r';
			} else if (opt.mute == 'volume_down') {
				cmd = 'MVDOWN\r';
Should read
case 'volume':
			if (opt.volume == 'volume_up') {
				cmd = 'MVUP\r';
			} else if (opt.volume == 'volume_down') {
				cmd = 'MVDOWN\r';

**Comment by theColourSpace** [comment]
I forgot to say "Thank you Jeffrey!" Hugely helpful, and a great guy to start programming my own. Will contribute a v2 at some point.

**Comment by JeffreyDavidsz** [comment]
You're welcome, have fun!
